# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Microsoft.Edge
PackageVersion: 89.0.774.68
FileExtensions:
- html
- htm
- url
- pdf
- crx
Protocols:
- http
- https
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a67b9c83-1671-45ab-982f-e02318eeffc9/MicrosoftEdgeEnterpriseX64.msi
  InstallerSha256: 6E1856B2972688D109F550B0A62C264E9829FF1F392E3BE0FC308900AEFD3455
  Scope: machine
  InstallerLocale: en-US
  ProductCode: "{99BBB765-AF90-3970-A395-239943FB9AF8}"
ManifestType: installer
ManifestVersion: 1.0.0

